## Cars

&nbsp;

### Indian population in 2021: 1,401 Bil


#### Data showcase about cars in India

&nbsp;

### like that...

&nbsp;

### Colect data about cars in india following these aspect:

    - Average price per color
    - Average price per brand
    - Quantity of cars per brand
    - Quantity of cars by transmission type
    - Average car age per region
    - Average engine power per fuel type

#### sort from higher to lower!

&nbsp;

In [1]:
import pandas as pd

In [2]:
# Loading data from the CSV file to panda framework

df = pd.read_csv('/content/car_details.csv')

In [3]:
# Dropping lines with null value

df.dropna(inplace=True)

In [4]:
# Treating data about the engines

df['Engine'] = df['Engine'].str.replace(' cc', '').astype(float)

In [5]:
df["Location"].unique()

array(['Pune', 'Ludhiana', 'Lucknow', 'Mangalore', 'Mumbai', 'Coimbatore',
       'Bangalore', 'Delhi', 'Raipur', 'Kanpur', 'Patna', 'Vadodara',
       'Hyderabad', 'Yamunanagar', 'Gurgaon', 'Jaipur', 'Deoghar', 'Agra',
       'Goa', 'Warangal', 'Jalandhar', 'Noida', 'Ahmedabad', 'Mohali',
       'Ghaziabad', 'Kolkata', 'Zirakpur', 'Nagpur', 'Thane', 'Faridabad',
       'Ranchi', 'Chandigarh', 'Amritsar', 'Chennai', 'Navi Mumbai',
       'Udupi', 'Jamshedpur', 'Aurangabad', 'Rudrapur', 'Nashik',
       'Varanasi', 'Salem', 'Dehradun', 'Valsad', 'Haldwani', 'Dharwad',
       'Surat', 'Indore', 'Karnal', 'Panchkula', 'Mysore', 'Rohtak',
       'Ambala Cantt', 'Samastipur', 'Panvel', 'Purnea', 'Bhubaneswar',
       'Kheda', 'Kollam', 'Meerut', 'Ernakulam', 'Kharar', 'Mirzapur',
       'Bhopal', 'Gorakhpur', 'Guwahati', 'Allahabad', 'Muzaffurpur',
       'Faizabad', 'Kota', 'Pimpri-Chinchwad', 'Dak. Kannada',
       'Ranga Reddy', 'Bulandshahar', 'Roorkee'], dtype=object)

In [6]:
# Calculating the average price per color

avrg_average_price_color = (df.groupby('Color')['Price'].mean()).round(2)

# Converting to brazillian reais

avrg_average_price_color = (avrg_average_price_color.divide(17)).round(2)

In [7]:
# Calculating the average price per brand

avrg_price_for_brand = df.groupby('Make')['Price'].mean()

# Converting to brazillian reais

avrg_price_for_brand = (avrg_price_for_brand.divide(17)).round(2)

In [8]:
# Calculating the quantity of cars per brand

qtty_cars_per_brand = df.groupby('Make').size()

In [9]:
# Calculating the quantity of cars by type of transmission

qtty_cars_per_transmission = df.groupby('Transmission').size()

In [10]:
# Calculate the average age per cars in the

avrg_age_per_region = (df.groupby('Location')['Year'].mean()).astype(int)

In [11]:
# Calculate the average engine power per type of fuel use

avrg_power_per_fuel = (df.groupby('Fuel Type')['Engine'].mean()).round(2)

In [12]:
print("\n Average car price per color:")
print(avrg_average_price_color.sort_values(ascending=False))

 Average car price per color:
Color
Yellow    262205.88
Black     175118.81
Blue      170147.76
Beige     131470.59
White     105869.32
Purple     95372.55
Bronze     83886.87
Green      81735.29
Maroon     78641.54
Red        76767.11
Brown      70043.72
Grey       69596.76
Silver     59547.35
Orange     54349.26
Gold       49592.59
Others     38572.19
Name: Price, dtype: float64

In [13]:
print("\n Average car price per brand:")
print(avrg_price_for_brand.sort_values(ascending=False))

 Average car price per brand:
Make
Ferrari          2058823.53
Rolls-Royce      1137254.90
Porsche           537254.90
Maserati          529411.76
Land Rover        398211.76
Lexus             266470.59
Mercedes-Benz     266225.30
BMW               235717.78
Jaguar            225900.45
Volvo             181816.17
MINI              173228.76
Audi              165230.81
MG                122470.58
Jeep              117863.97
Isuzu             114441.18
Toyota            105102.82
Kia                92347.83
Ford               88406.76
Skoda              81462.64
Mitsubishi         79338.24
Mahindra           66064.17
Tata               58769.71
Ssangyong          50000.00
Volkswagen         45984.59
Hyundai            43773.53
Honda              37330.04
Maruti Suzuki      33020.98
Nissan             28098.04
Renault            27622.43
Fiat               22058.82
Chevrolet          17558.81
Datsun             17522.06
Name: Price, dtype: float64

In [14]:
print("\n Quantity of cars per brand:")
print(qtty_cars_per_brand.sort_values(ascending=False))

 Quantity of cars per brand:
Make
Maruti Suzuki    398
Hyundai          333
Mercedes-Benz    159
Honda            149
Toyota           123
Audi             118
Mahindra         110
BMW               89
Tata              47
Ford              47
Renault           43
Volkswagen        42
Skoda             37
Land Rover        30
Kia               23
Volvo             16
Jeep              16
Nissan            15
MG                13
Jaguar            13
Porsche           12
MINI               9
Datsun             8
Lexus              5
Mitsubishi         4
Chevrolet          4
Rolls-Royce        3
Ssangyong          3
Isuzu              2
Maserati           1
Fiat               1
Ferrari            1
dtype: int64

In [15]:
print("\n Quantity of cars by type of transmission:")
print(qtty_cars_per_transmission.sort_values(ascending=False))

 Quantity of cars by type of transmission:
Transmission
Manual       1037
Automatic     837
dtype: int64

In [16]:
print("\n Average age of cars per region:")
print(avrg_age_per_region.sort_values(ascending=False))

 Average age of cars per region:
Location
Gorakhpur      2021
Mangalore      2020
Ranga Reddy    2019
Ghaziabad      2018
Kota           2018
               ...
Deoghar        2013
Roorkee        2013
Faizabad       2013
Jamshedpur     2013
Salem          2012
Name: Year, Length: 75, dtype: int64

In [18]:
print("\n average engine power per type of fuel used:")
print(avrg_power_per_fuel.sort_values(ascending=False))

 average engine power per type of fuel used:
Fuel Type
Hybrid          2489.33
Diesel          1942.32
Petrol          1432.71
Petrol + CNG    1197.00
LPG             1035.75
CNG             1029.22
CNG + CNG        796.00
Name: Engine, dtype: float64